var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/[...nextauth]/route.js")
R.c("server/chunks/node_modules_bcryptjs_index_93c6dc43.js")
R.c("server/chunks/node_modules_next_c0d7f167._.js")
R.c("server/chunks/node_modules_@auth_core_d21088c9._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_ab03e039._.js")
R.c("server/chunks/[root-of-the-server]__ba7f4bb3._.js")
R.c("server/chunks/[root-of-the-server]__4d871c2c._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_[___nextauth]_route_actions_1c865db8.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/auth/[...nextauth]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/auth/[...nextauth]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
